version: '2'
services:
  db:
    image: mongo:4.4.3
    restart: always
    # environment:
    #   # mongodb client connection
    #   MONGO_INITDB_ROOT_USERNAME: mongoroot
    #   MONGO_INITDB_ROOT_PASSWORD: mongosecret
    ports:
      - "27017:27017"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rspec --format documentation && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/dokerize-rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db