development:
  clients:
    default:
      database: test_development
      hosts:
        # use localhost if ur are using  network_mode: "host" in docker compose or --net="host" in docker run
        # - mongo:27018
        # - host.docker.internal:27017
        # - 172.18.0.1:27017
        - localhost:27018
      options:
  options:

test:
  clients:
    default:
      database: test_test
      hosts:
        - localhost:27018
      options:
  options: